modules = [
    "syncthing",
    "disk",
    "xkblayout",
    "cpu",
    "load",
    "temperature",
    "backlight",
    "battery",
    "datetime",
]

[datetime]
format = "strftime::%a %d %b %H:%M:%S"

[xkblayout]
layouts = ["de nodeadkeys", "us"]
