(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)

;; fix terminal in tmux
(add-to-list 'term-file-aliases
    '("tmux-256color" . "xterm-256color")
    '("tmux" . "xterm-256color"))

;; evil mode for vim keybindings
(setq evil-want-C-u-scroll t)
(require 'evil)
(require 'evil-mc)
(evil-mode 1)
(evil-commentary-mode)
(global-evil-mc-mode 1)

;; autocompletion
;; (require 'helm-config)
(require 'company)                                   
(add-to-list 'company-backends 'company-c-headers)

;; (helm-mode 1)
;; (global-set-key (kbd "M-x") 'helm-M-x)

;; I want a Git gutter.
(global-git-gutter-mode +1)

;; Highlight matching brackets.
(show-paren-mode 1)

;; No toolbar.
(tool-bar-mode -1)

;; Disable the menu bar by default. Use M-x menu-bar-mode to make it re-appear.
(menu-bar-mode -1)

;; Better than the default.
(load-theme 'tango-dark t)

;; ido-mode has a *much* better buffer selection (and file opening) :).
(ido-mode)

;; use settings from .editorconfig file when present
(require 'editorconfig)
(editorconfig-mode 1)

;; do not clutter the filesystem with stuff
(if (> emacs-major-version 26)
    (auto-save-visited-mode))

;; show line numbers
(if (> emacs-major-version 26)
    (global-display-line-numbers-mode)
  (global-linum-mode
   (setq linum-format "%d ")))

(setq column-number-mode t)

;; remember cursor position, for emacs 25.1 or later
(save-place-mode 1)

(defalias 'yes-or-no-p 'y-or-n-p)

(setq
 backup-directory-alist `(("." . ,(concat user-emacs-directory "backups")))
 delete-old-versions t
 backup-by-copying t
 kept-new-versions 6
 kept-old-versions 2
 version-control t)

;; config for c
(setq c-default-style "linux")

;; config for go
(require 'company-go)                               
(add-hook 'after-init-hook 'global-company-mode)

(eval-after-load "company"
  '(add-to-list 'company-backends 'company-go))

(set 'gofmt-command "goimports")

(defun go-hook ()
  ;; Run gofmt before saving
  (add-hook 'before-save-hook 'gofmt-before-save)
  ;; Jump to the definition of the symbol under the cursor.
  ;; (Jump back with M-*)
  (local-set-key (kbd "M-.") 'go-guru-definition)
  (local-set-key (kbd "C-c d") 'godoc-at-point)
  ;; One tab will be displayed as 4 spaces.
  (set 'tab-width 4)
  ;; Enable eldoc (displays function signatures in the minibuf).
  (go-eldoc-setup))
(add-hook 'go-mode-hook 'go-hook)

;; config for python
(setq python-shell-interpreter "python3")

(eval-after-load "company"
  '(add-to-list 'company-backends 'company-anaconda))
(add-hook 'python-mode-hook 'anaconda-mode)

;; email
(setq                                                                                                                                                                                  
mu4e-maildir       "~/mail"   ;; top-level Maildir
mu4e-sent-folder   "/sent"       ;; folder for sent messages
mu4e-drafts-folder "/drafts"     ;; unfinished messages
mu4e-trash-folder  "/trash"      ;; trashed messages
mu4e-refile-folder "/archive")   ;; saved messages

;; autogenerated (??)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   (quote
    ("a8245b7cc985a0610d71f9852e9f2767ad1b852c2bdea6f4aadc12cce9c4d6d0" default)))
 '(package-selected-packages
   (quote
    (adoc-mode evil-mc magit helm projectile evil-collection ggtags spacemacs-theme evil-commentary neotree evil-goggles git-gutter evil company-go company-c-headers company-anaconda))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
