[theme]
name = "plain"

[theme.overrides]
idle_fg = "#ffffff"
good_fg = "#00ff00"
info_fg = "#00ff00"
warning_fg = "#ffa500"
critical_fg = "#ff0000"

[icons]
name = "awesome5"

[[block]]
block = "music"
buttons = ["play", "prev", "next"]

[[block]]
block = "networkmanager"
# on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
ap_format = "{ssid} [{strength}]"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

# [[block]]
# block = "temperature"
# collapsed = false

[[block]]
block = "sound"

[[block]]
block = "time"
format = "KW%V: %a %d.%m.%y %R"
locale = "de_DE"
