[theme]
name = "plain"

[theme.overrides]
idle_fg = "#ffffff"
good_fg = "#00ff00"
info_fg = "#00ff00"
warning_fg = "#ffa500"
critical_fg = "#ff0000"

[icons]
name = "awesome5"

[icons.overrides]
# time = ""
# net_wired = ""
microphone_full = "\uf130"
microphone_half = "\uf130"
microphone_empty = "\uf130"
microphone_muted =  "\uf131"

# [[block]]
# block = "networkmanager"
# # on_click = "alacritty -e nmtui"
# interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
# interface_name_include = []
# ap_format = "{ssid} [{strength}]"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
# format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false

[[block]]
block = "battery"
driver = "upower"
format = "{percentage} {time}"

[[block]]
block = "backlight"
device = "intel_backlight"
invert_icons = true

[[block]]
block = "sound"
device_kind = "sink"

[[block]]
block = "sound"
device_kind = "source"

[[block]]
block = "time"
format = "KW%V: %a %d.%m.%y %R"
locale = "de_DE"

