(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  (when no-ssl
    (warn "\
Your version of Emacs does not support SSL connections,
which is unsafe because it allows man-in-the-middle attacks.
There are two things you can do about this warning:
1. Install an Emacs version that does support SSL and be safe.
2. Remove this warning from your init file so you won't see it again."))
  ;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
  ;;(add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
  (add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
  (when (< emacs-major-version 24)
    ;; For important compatibility libraries like cl-lib
    (add-to-list 'package-archives (cons "gnu" (concat proto "://elpa.gnu.org/packages/")))))
(package-initialize)

;;
;; Plugins
;;

;; evil mode for vim keybindings
(setq evil-want-C-u-scroll t)
(require 'evil)
(evil-mode 1)

;; use settings from .editorconfig file when present
;; nice to have, thus optional plugin
(if (require 'editorconfig nil t)
    (editorconfig-mode 1))

;;
;; editor settings
;;

;; fix terminal in tmux and in kitty
(add-to-list 'term-file-aliases
    '("tmux-256color" . "xterm-256color"))
(add-to-list 'term-file-aliases
    '("tmux" . "xterm-256color"))
(add-to-list 'term-file-aliases
    '("xterm-kitty" . "xterm-256color"))

;; I almost always use a dark terminal. Auto detection only works in tmux. ?
(setq frame-background-mode 'dark)

;; enable mouse
(xterm-mouse-mode 1)

;; No toolbar.
(tool-bar-mode -1)

;; Disable the menu bar by default. Use M-x menu-bar-mode to make it re-appear.
(menu-bar-mode -1)

;; Enable minibuffer history.
(savehist-mode 1)

;; Show column in status bar.
(setq column-number-mode t)

;; Highlight matching brackets.
(show-paren-mode 1)

;; remember cursor position, for emacs 25.1 or later
(save-place-mode 1)

;; ido-mode has a *much* better buffer selection (and file opening) :).
(ido-mode)

(global-display-line-numbers-mode)
(auto-save-visited-mode)

(defalias 'yes-or-no-p 'y-or-n-p)

;; Do not clutter filesystem with backup files...
;; store all backup and autosave files in the tmp dir
(setq backup-directory-alist
      `((".*" . ,temporary-file-directory)))
(setq auto-save-file-name-transforms
      `((".*" ,temporary-file-directory t)))

;; (setq
;;  backup-directory-alist `(("." . ,(concat user-emacs-directory "backups")))
;;  delete-old-versions t
;;  backup-by-copying t
;;  kept-new-versions 6
;;  kept-old-versions 2
;;  version-control t)

;; Highlight useful keywords
(add-hook 'prog-mode-hook
           (lambda ()
            (font-lock-add-keywords nil
             '(("\\<\\(FIXME\\|TODO\\|BUG\\|XXX\\):" 1
                font-lock-warning-face t)))))

;;
;; keybindings


(global-set-key (kbd "M-/") 'hippie-expand)
;; C-x C-; does not work in a terminal.
(global-set-key (kbd "C-x /") 'comment-line)

;;
;; whitespace settings
;;

(setq whitespace-line-column 80)
(setq whitespace-style '(face lines-tail trailing))

;; only enable whitespace settings in programming modes
(add-hook 'prog-mode-hook 'whitespace-mode)

;;
;; Programming Configuration
;;

;; c
(setq c-default-style "linux")

;; go
(set 'gofmt-command "goimports")
(add-hook 'before-save-hook 'gofmt-before-save)

;; python
(setq python-shell-interpreter "python3")

;; (eval-after-load "company"
;;   '(add-to-list 'company-backends 'company-anaconda))
;; (add-hook 'python-mode-hook 'anaconda-mode)

;(require 'mu4e)
;
;(define-key mu4e-compose-mode-map (kbd "C-c u") 'mu4e-update-mail-and-index)
;
;;; email
;(setq message-send-mail-function 'smtpmail-send-it
;    smtpmail-smtp-server  "coruscant.sevenbyte.org"
;    smtpmail-stream-type  'starttls
;    smtpmail-smtp-service 587
;    user-full-name "Stefan Tatschner"
;    user-mail-address "stefan@rumpelsepp.org"
;    user-login-name user-mail-address
;    mu4e-get-mail-command "mbsync private"
;    mml-secure-openpgp-encrypt-to-self t
;    mml-secure-openpgp-sign-with-sender t
;    message-citation-line-function 'message-insert-formatted-citation-line)
;
;(setq
; mu4e-maildir       "~/mail"   ;; top-level Maildir
; mu4e-sent-folder   "/stefan@rumpelsepp.org/Sent"       ;; folder for sent messages
; mu4e-drafts-folder "/stefan@rumpelsepp.org/Drafts"     ;; unfinished messages
; mu4e-trash-folder  "/stefan@rumpelsepp.org/Trash"      ;; trashed messages
; mu4e-refile-folder "/stefan@rumpelsepp.org/Archive")   ;; saved messages
;
;(add-to-list 'mu4e-bookmarks
;  (make-mu4e-bookmark
;    :name  "INBOX"
;    :query "maildir:/stefan@rumpelsepp.org/INBOX"
;    :key ?i))
;
;;; autogenerated (??)
;(custom-set-variables
; ;; custom-set-variables was added by Custom.
; ;; If you edit it by hand, you could mess it up, so be careful.
; ;; Your init file should contain only one such instance.
; ;; If there is more than one, they won't work right.
; '(auth-source-save-behavior nil))
;(custom-set-faces
; ;; custom-set-faces was added by Custom.
; ;; If you edit it by hand, you could mess it up, so be careful.
; ;; Your init file should contain only one such instance.
; ;; If there is more than one, they won't work right.
; )
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (notmuch evil))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
