(require 'package)
(package-initialize)

;;
;; Plugins
;;

;; evil mode for vim keybindings
(setq evil-want-C-u-scroll t)
(require 'evil)
(evil-mode 1)

;; use evil mode as usual in git commit editor
(if (require 'git-commit nil t)
    (add-hook 'git-commit-mode-hook 'evil-normal-state))

;; use settings from .editorconfig file when present
;; nice to have, thus optional plugin
(if (require 'editorconfig nil t)
    (editorconfig-mode 1))

;;
;; editor settings
;;

;; fix terminal in tmux and in kitty
(add-to-list 'term-file-aliases
    '("tmux-256color" . "xterm-256color"))
(add-to-list 'term-file-aliases
    '("tmux" . "xterm-256color"))
(add-to-list 'term-file-aliases
    '("xterm-kitty" . "xterm-256color"))

;; I almost always use a dark terminal. Auto detection only works in tmux. ?
(setq frame-background-mode 'dark)

;; enable mouse
(xterm-mouse-mode 1)

;; No toolbar.
(tool-bar-mode -1)

;; Disable the menu bar by default. Use M-x menu-bar-mode to make it re-appear.
(menu-bar-mode -1)

;; Enable minibuffer history.
(savehist-mode 1)

;; Highlight matching brackets.
(show-paren-mode 1)

;; remember cursor position, for emacs 25.1 or later
(save-place-mode 1)

;; ido-mode has a *much* better buffer selection (and file opening) :).
(ido-mode)

;; emacs 26 options
;; TODO: might not work ?
(if (> emacs-major-version 26)
    ;; do not clutter the filesystem with stuff
    ((auto-save-visited-mode)
    ;; show line numbers, on emacs >= 26
    (global-display-line-numbers-mode)))

(defalias 'yes-or-no-p 'y-or-n-p)

;; Do not clutter filesystem with backup files...
(setq
 backup-directory-alist `(("." . ,(concat user-emacs-directory "backups")))
 delete-old-versions t
 backup-by-copying t
 kept-new-versions 6
 kept-old-versions 2
 version-control t)

;; Highlight useful keywords
(add-hook 'prog-mode-hook
           (lambda ()
            (font-lock-add-keywords nil
             '(("\\<\\(FIXME\\|TODO\\|BUG\\|XXX\\):" 1
                font-lock-warning-face t)))))

;;
;; keybindings
;;

(global-set-key (kbd "M-/") 'hippie-expand)
;; Bug? the default shortcut does not work?
(global-set-key (kbd "C-x ;") 'comment-line)

;;
;; whitespace settings
;;

(setq whitespace-line-column 80)
(setq whitespace-style '(face lines-tail trailing))

;; only enable whitespace settings in programming modes
(add-hook 'prog-mode-hook 'whitespace-mode)

;;
;; Programming Configuration
;;

;; c
(setq c-default-style "linux")

;; go

;; (set 'gofmt-command "goimports")

;; python
(setq python-shell-interpreter "python3")

;; (eval-after-load "company"
;;   '(add-to-list 'company-backends 'company-anaconda))
;; (add-hook 'python-mode-hook 'anaconda-mode)

;; email
(setq
mu4e-maildir       "~/mail"   ;; top-level Maildir
mu4e-sent-folder   "/sent"       ;; folder for sent messages
mu4e-drafts-folder "/drafts"     ;; unfinished messages
mu4e-trash-folder  "/trash"      ;; trashed messages
mu4e-refile-folder "/archive")   ;; saved messages

;; autogenerated (??)
